import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const buildState = v.union(
  v.literal("queued"),
  v.literal("running"),
  v.literal("validating"),
  v.literal("failed"),
  v.literal("needs_intervention"),
  v.literal("succeeded"),
  v.literal("canceled"),
);

export default defineSchema({
  users: defineTable({
    identitySubject: v.string(),
    name: v.string(),
    email: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_identity_subject", ["identitySubject"]),
  channels: defineTable({
    slug: v.string(),
    name: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_slug", ["slug"]),
  channelMemberships: defineTable({
    channelId: v.id("channels"),
    userId: v.id("users"),
    role: v.union(v.literal("owner"), v.literal("member")),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_channel_user", ["channelId", "userId"])
    .index("by_user_channel", ["userId", "channelId"]),
  projects: defineTable({
    channelId: v.id("channels"),
    creatorMembershipId: v.id("channelMemberships"),
    name: v.string(),
    description: v.optional(v.string()),
    currentScriptVersionId: v.optional(v.id("scriptVersions")),
    currentScriptVersionNumber: v.optional(v.number()),
    currentNarrationVersionId: v.optional(v.id("narrationVersions")),
    currentNarrationVersionNumber: v.optional(v.number()),
    currentCompositionVersionId: v.optional(v.id("compositionVersions")),
    currentCompositionVersionNumber: v.optional(v.number()),
    status: v.union(v.literal("active"), v.literal("archived")),
    createdAt: v.number(),
    updatedAt: v.number(),
    archivedAt: v.optional(v.number()),
  })
    .index("by_channel_updated", ["channelId", "updatedAt"])
    .index("by_channel_status", ["channelId", "status"]),
  projectSources: defineTable({
    channelId: v.id("channels"),
    projectId: v.id("projects"),
    addedByMembershipId: v.id("channelMemberships"),
    kind: v.union(v.literal("url"), v.literal("file")),
    status: v.union(v.literal("active"), v.literal("removed")),
    title: v.string(),
    normalizedUrl: v.optional(v.string()),
    storageId: v.optional(v.id("_storage")),
    fileName: v.optional(v.string()),
    mediaType: v.string(),
    byteSize: v.number(),
    contentHash: v.string(),
    hashKind: v.union(v.literal("reference_sha256"), v.literal("file_sha256")),
    createdAt: v.number(),
    updatedAt: v.number(),
    removedAt: v.optional(v.number()),
  })
    .index("by_project_status_created", ["projectId", "status", "createdAt"])
    .index("by_storage_id", ["storageId"]),
  scriptVersions: defineTable({
    channelId: v.id("channels"),
    projectId: v.id("projects"),
    createdByMembershipId: v.id("channelMemberships"),
    version: v.number(),
    content: v.string(),
    provenance: v.union(v.literal("manual"), v.literal("import")),
    createdAt: v.number(),
  })
    .index("by_project_version", ["projectId", "version"])
    .index("by_project_created", ["projectId", "createdAt"]),
  narrationVersions: defineTable({
    channelId: v.id("channels"),
    projectId: v.id("projects"),
    scriptVersionId: v.optional(v.id("scriptVersions")),
    createdByMembershipId: v.id("channelMemberships"),
    version: v.number(),
    provenance: v.union(v.literal("generated"), v.literal("upload")),
    storageId: v.id("_storage"),
    mediaType: v.string(),
    durationMs: v.number(),
    timingSegments: v.array(
      v.object({
        index: v.number(),
        startMs: v.number(),
        endMs: v.number(),
        text: v.string(),
      }),
    ),
    provider: v.optional(v.string()),
    model: v.optional(v.string()),
    fileName: v.optional(v.string()),
    audioCodec: v.optional(v.string()),
    sampleRate: v.optional(v.number()),
    channels: v.optional(v.number()),
    usageCharacters: v.optional(v.number()),
    estimatedCostUsd: v.optional(v.number()),
    wallTimeMs: v.optional(v.number()),
    createdAt: v.number(),
  })
    .index("by_project_version", ["projectId", "version"])
    .index("by_script_version", ["scriptVersionId"]),
  beats: defineTable({
    channelId: v.id("channels"),
    projectId: v.id("projects"),
    narrationVersionId: v.id("narrationVersions"),
    createdByMembershipId: v.id("channelMemberships"),
    order: v.number(),
    startMs: v.number(),
    endMs: v.number(),
    title: v.string(),
    summary: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_project_narration_order", [
      "projectId",
      "narrationVersionId",
      "order",
    ])
    .index("by_project_created", ["projectId", "createdAt"]),
  compositionVersions: defineTable({
    channelId: v.id("channels"),
    projectId: v.id("projects"),
    narrationVersionId: v.id("narrationVersions"),
    createdByMembershipId: v.id("channelMemberships"),
    version: v.number(),
    schemaVersion: v.literal(1),
    provenance: v.union(v.literal("manual"), v.literal("agent")),
    compositionJson: v.string(),
    createdAt: v.number(),
  }).index("by_project_version", ["projectId", "version"]),
  compositionProposals: defineTable({
    channelId: v.id("channels"),
    projectId: v.id("projects"),
    createdByMembershipId: v.id("channelMemberships"),
    baseCompositionVersionId: v.id("compositionVersions"),
    request: v.string(),
    state: v.union(
      v.literal("reviewable"),
      v.literal("invalid"),
      v.literal("accepted"),
      v.literal("rejected"),
    ),
    proposedCompositionJson: v.optional(v.string()),
    patchJson: v.optional(v.string()),
    rationale: v.string(),
    validationEvidenceJson: v.string(),
    toolActivityJson: v.string(),
    provider: v.string(),
    model: v.string(),
    attempt: v.number(),
    maxAttempts: v.number(),
    inputTokens: v.number(),
    outputTokens: v.number(),
    estimatedCostUsd: v.number(),
    acceptedCompositionVersionId: v.optional(v.id("compositionVersions")),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_project_created", ["projectId", "createdAt"]),
  narrationJobs: defineTable({
    channelId: v.id("channels"),
    projectId: v.id("projects"),
    kind: v.optional(v.union(v.literal("generated"), v.literal("upload"))),
    scriptVersionId: v.optional(v.id("scriptVersions")),
    sourceStorageId: v.optional(v.id("_storage")),
    sourceFileName: v.optional(v.string()),
    sourceMediaType: v.optional(v.string()),
    createdByMembershipId: v.id("channelMemberships"),
    provider: v.string(),
    model: v.string(),
    state: v.union(
      v.literal("queued"),
      v.literal("running"),
      v.literal("succeeded"),
      v.literal("failed"),
      v.literal("canceled"),
      v.literal("needs_intervention"),
    ),
    attempt: v.number(),
    maxAttempts: v.number(),
    cancelRequested: v.boolean(),
    leaseOwner: v.optional(v.string()),
    leaseExpiresAt: v.optional(v.number()),
    heartbeatAt: v.optional(v.number()),
    narrationVersionId: v.optional(v.id("narrationVersions")),
    terminalCode: v.optional(v.string()),
    terminalMessage: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_state_created", ["state", "createdAt"])
    .index("by_state_lease", ["state", "leaseExpiresAt"])
    .index("by_project_created", ["projectId", "createdAt"]),
  narrationJobEvents: defineTable({
    jobId: v.id("narrationJobs"),
    state: v.union(
      v.literal("queued"),
      v.literal("running"),
      v.literal("succeeded"),
      v.literal("failed"),
      v.literal("canceled"),
      v.literal("needs_intervention"),
    ),
    kind: v.string(),
    message: v.string(),
    createdAt: v.number(),
  }).index("by_job_created", ["jobId", "createdAt"]),
  componentConversationThreads: defineTable({
    channelId: v.string(),
    threadId: v.string(),
    phase: v.union(
      v.literal("dialogue"),
      v.literal("authoring"),
      v.literal("review"),
    ),
    selectedBaseVersionId: v.optional(v.id("componentVersions")),
    themeJson: v.string(),
    sessionRef: v.optional(v.string()),
    contextTokens: v.optional(v.number()),
    contextWindow: v.optional(v.number()),
    contextPercent: v.optional(v.number()),
    totalInputTokens: v.optional(v.number()),
    totalOutputTokens: v.optional(v.number()),
    totalCacheReadTokens: v.optional(v.number()),
    totalCacheWriteTokens: v.optional(v.number()),
    estimatedCostUsd: v.optional(v.number()),
    compactionCount: v.optional(v.number()),
    lastCompactedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_channel_thread", ["channelId", "threadId"]),
  componentConversationMessages: defineTable({
    channelId: v.string(),
    threadId: v.string(),
    messageId: v.string(),
    role: v.union(v.literal("user"), v.literal("assistant")),
    state: v.union(
      v.literal("streaming"),
      v.literal("complete"),
      v.literal("failed"),
    ),
    content: v.string(),
    safeStatus: v.optional(v.string()),
    transitionBrief: v.optional(v.string()),
    inputTokens: v.optional(v.number()),
    outputTokens: v.optional(v.number()),
    cacheReadTokens: v.optional(v.number()),
    cacheWriteTokens: v.optional(v.number()),
    costUsd: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_thread_created", ["channelId", "threadId", "createdAt"])
    .index("by_message", ["channelId", "threadId", "messageId"]),
  components: defineTable({
    channelId: v.string(),
    componentId: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    latestApprovedVersionId: v.optional(v.id("componentVersions")),
  }).index("by_channel_component", ["channelId", "componentId"]),
  componentCandidates: defineTable({
    channelId: v.string(),
    componentId: v.string(),
    declaredVersion: v.string(),
    buildJobId: v.id("componentBuildJobs"),
    sourceHash: v.string(),
    candidateRef: v.string(),
    validationEvidenceJson: v.string(),
    inputSchemaJson: v.string(),
    inputSchemaFingerprint: v.string(),
    compatibilityJson: v.string(),
    fixturesJson: v.string(),
    dimensionsJson: v.string(),
    baseVersionId: v.optional(v.id("componentVersions")),
    status: v.union(
      v.literal("reviewable"),
      v.literal("approved"),
      v.literal("rejected"),
      v.literal("changes_requested"),
    ),
    compatibilityWarning: v.optional(v.string()),
    decisionNote: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_build_job", ["buildJobId"])
    .index("by_channel_component_created", [
      "channelId",
      "componentId",
      "createdAt",
    ]),
  componentVersions: defineTable({
    channelId: v.string(),
    componentId: v.string(),
    version: v.string(),
    candidateId: v.id("componentCandidates"),
    buildJobId: v.id("componentBuildJobs"),
    sourceHash: v.string(),
    candidateRef: v.string(),
    validationEvidenceJson: v.string(),
    inputSchemaJson: v.string(),
    inputSchemaFingerprint: v.string(),
    fixturesJson: v.string(),
    dimensionsJson: v.string(),
    previousVersionId: v.optional(v.id("componentVersions")),
    approvedAt: v.number(),
  })
    .index("by_candidate", ["candidateId"])
    .index("by_channel_component_version", [
      "channelId",
      "componentId",
      "version",
    ])
    .index("by_channel_component_approved", [
      "channelId",
      "componentId",
      "approvedAt",
    ]),
  projectComponentPins: defineTable({
    channelId: v.string(),
    projectId: v.string(),
    componentId: v.string(),
    versionId: v.id("componentVersions"),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_channel_project_component", [
    "channelId",
    "projectId",
    "componentId",
  ]),
  componentBuildJobs: defineTable({
    channelId: v.string(),
    threadId: v.string(),
    turnId: v.string(),
    parentCandidateId: v.optional(v.string()),
    baseSnapshotId: v.optional(v.string()),
    sourceSnapshot: v.string(),
    sourceHash: v.string(),
    state: buildState,
    attempt: v.number(),
    maxAttempts: v.number(),
    repairAttempt: v.optional(v.number()),
    maxRepairAttempts: v.optional(v.number()),
    cancelRequested: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
    leaseOwner: v.optional(v.string()),
    leaseExpiresAt: v.optional(v.number()),
    heartbeatAt: v.optional(v.number()),
    terminalCode: v.optional(v.string()),
    terminalMessage: v.optional(v.string()),
    candidateRef: v.optional(v.string()),
    boundedStdout: v.optional(v.string()),
    boundedStderr: v.optional(v.string()),
    validationEvidenceJson: v.optional(v.string()),
    repairTurnId: v.optional(v.id("authoringTurns")),
    candidateId: v.optional(v.id("componentCandidates")),
  })
    .index("by_state_created", ["state", "createdAt"])
    .index("by_state_lease", ["state", "leaseExpiresAt"])
    .index("by_thread_turn", ["threadId", "turnId"])
    .index("by_channel_thread_turn", ["channelId", "threadId", "turnId"])
    .index("by_channel_thread_created", ["channelId", "threadId", "createdAt"]),
  componentBuildEvents: defineTable({
    jobId: v.id("componentBuildJobs"),
    createdAt: v.number(),
    kind: v.string(),
    state: buildState,
    message: v.string(),
  }).index("by_job_created", ["jobId", "createdAt"]),
  authoringThreads: defineTable({
    channelId: v.string(),
    threadId: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    latestTurnId: v.optional(v.string()),
  }).index("by_channel_thread", ["channelId", "threadId"]),
  authoringTurns: defineTable({
    channelId: v.string(),
    threadId: v.string(),
    turnId: v.string(),
    userRequest: v.string(),
    acceptanceCriteria: v.array(v.string()),
    baseSource: v.string(),
    baseSourceHash: v.string(),
    parentCandidateId: v.optional(v.string()),
    baseSnapshotId: v.optional(v.string()),
    channelThemeJson: v.string(),
    assetsMetadataJson: v.string(),
    priorSummaries: v.array(v.string()),
    rootTurnId: v.optional(v.string()),
    repairAttempt: v.optional(v.number()),
    maxRepairAttempts: v.optional(v.number()),
    validationEvidenceJson: v.optional(v.string()),
    state: v.union(
      v.literal("queued"),
      v.literal("running"),
      v.literal("candidate_submitted"),
      v.literal("failed"),
      v.literal("needs_intervention"),
      v.literal("canceled"),
    ),
    attempt: v.number(),
    maxAttempts: v.number(),
    cancelRequested: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
    leaseOwner: v.optional(v.string()),
    leaseExpiresAt: v.optional(v.number()),
    heartbeatAt: v.optional(v.number()),
    maxWallTimeMs: v.number(),
    maxModelTurns: v.number(),
    maxToolCalls: v.number(),
    maxTokens: v.number(),
    maxCostUsd: v.number(),
    contextHash: v.optional(v.string()),
    sessionRef: v.optional(v.string()),
    assistantSummary: v.optional(v.string()),
    assistantText: v.optional(v.string()),
    toolCalls: v.optional(v.number()),
    modelTurns: v.optional(v.number()),
    inputTokens: v.optional(v.number()),
    outputTokens: v.optional(v.number()),
    cacheReadTokens: v.optional(v.number()),
    cacheWriteTokens: v.optional(v.number()),
    costUsd: v.optional(v.number()),
    wallTimeMs: v.optional(v.number()),
    terminalCode: v.optional(v.string()),
    terminalMessage: v.optional(v.string()),
    candidateSourceHash: v.optional(v.string()),
    buildJobId: v.optional(v.id("componentBuildJobs")),
  })
    .index("by_state_created", ["state", "createdAt"])
    .index("by_state_lease", ["state", "leaseExpiresAt"])
    .index("by_channel_thread_turn", ["channelId", "threadId", "turnId"])
    .index("by_channel_thread_created", ["channelId", "threadId", "createdAt"]),
  authoringEvents: defineTable({
    turnId: v.id("authoringTurns"),
    createdAt: v.number(),
    kind: v.string(),
    state: v.string(),
    message: v.string(),
  }).index("by_turn_created", ["turnId", "createdAt"]),
  authoringToolActivities: defineTable({
    turnId: v.id("authoringTurns"),
    attempt: v.number(),
    sequence: v.number(),
    createdAt: v.number(),
    name: v.string(),
    status: v.string(),
    inputSummary: v.string(),
    outputSummary: v.string(),
    durationMs: v.number(),
  }).index("by_turn_attempt_sequence", ["turnId", "attempt", "sequence"]),
});
