import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const buildState = v.union(
  v.literal("queued"),
  v.literal("running"),
  v.literal("validating"),
  v.literal("failed"),
  v.literal("needs_intervention"),
  v.literal("succeeded"),
  v.literal("canceled"),
);

export default defineSchema({
  componentBuildJobs: defineTable({
    channelId: v.string(),
    threadId: v.string(),
    turnId: v.string(),
    parentCandidateId: v.optional(v.string()),
    baseSnapshotId: v.optional(v.string()),
    sourceSnapshot: v.string(),
    sourceHash: v.string(),
    state: buildState,
    attempt: v.number(),
    maxAttempts: v.number(),
    repairAttempt: v.optional(v.number()),
    maxRepairAttempts: v.optional(v.number()),
    cancelRequested: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
    leaseOwner: v.optional(v.string()),
    leaseExpiresAt: v.optional(v.number()),
    heartbeatAt: v.optional(v.number()),
    terminalCode: v.optional(v.string()),
    terminalMessage: v.optional(v.string()),
    candidateRef: v.optional(v.string()),
    boundedStdout: v.optional(v.string()),
    boundedStderr: v.optional(v.string()),
    validationEvidenceJson: v.optional(v.string()),
    repairTurnId: v.optional(v.id("authoringTurns")),
  })
    .index("by_state_created", ["state", "createdAt"])
    .index("by_state_lease", ["state", "leaseExpiresAt"])
    .index("by_thread_turn", ["threadId", "turnId"])
    .index("by_channel_thread_turn", ["channelId", "threadId", "turnId"])
    .index("by_channel_thread_created", ["channelId", "threadId", "createdAt"]),
  componentBuildEvents: defineTable({
    jobId: v.id("componentBuildJobs"),
    createdAt: v.number(),
    kind: v.string(),
    state: buildState,
    message: v.string(),
  }).index("by_job_created", ["jobId", "createdAt"]),
  authoringThreads: defineTable({
    channelId: v.string(),
    threadId: v.string(),
    createdAt: v.number(),
    updatedAt: v.number(),
    latestTurnId: v.optional(v.string()),
  }).index("by_channel_thread", ["channelId", "threadId"]),
  authoringTurns: defineTable({
    channelId: v.string(),
    threadId: v.string(),
    turnId: v.string(),
    userRequest: v.string(),
    acceptanceCriteria: v.array(v.string()),
    baseSource: v.string(),
    baseSourceHash: v.string(),
    parentCandidateId: v.optional(v.string()),
    baseSnapshotId: v.optional(v.string()),
    channelThemeJson: v.string(),
    assetsMetadataJson: v.string(),
    priorSummaries: v.array(v.string()),
    rootTurnId: v.optional(v.string()),
    repairAttempt: v.optional(v.number()),
    maxRepairAttempts: v.optional(v.number()),
    validationEvidenceJson: v.optional(v.string()),
    state: v.union(
      v.literal("queued"),
      v.literal("running"),
      v.literal("candidate_submitted"),
      v.literal("failed"),
      v.literal("needs_intervention"),
      v.literal("canceled"),
    ),
    attempt: v.number(),
    maxAttempts: v.number(),
    cancelRequested: v.boolean(),
    createdAt: v.number(),
    updatedAt: v.number(),
    leaseOwner: v.optional(v.string()),
    leaseExpiresAt: v.optional(v.number()),
    heartbeatAt: v.optional(v.number()),
    maxWallTimeMs: v.number(),
    maxModelTurns: v.number(),
    maxToolCalls: v.number(),
    maxTokens: v.number(),
    maxCostUsd: v.number(),
    contextHash: v.optional(v.string()),
    sessionRef: v.optional(v.string()),
    assistantSummary: v.optional(v.string()),
    toolCalls: v.optional(v.number()),
    modelTurns: v.optional(v.number()),
    inputTokens: v.optional(v.number()),
    outputTokens: v.optional(v.number()),
    cacheReadTokens: v.optional(v.number()),
    cacheWriteTokens: v.optional(v.number()),
    costUsd: v.optional(v.number()),
    wallTimeMs: v.optional(v.number()),
    terminalCode: v.optional(v.string()),
    terminalMessage: v.optional(v.string()),
    candidateSourceHash: v.optional(v.string()),
    buildJobId: v.optional(v.id("componentBuildJobs")),
  })
    .index("by_state_created", ["state", "createdAt"])
    .index("by_state_lease", ["state", "leaseExpiresAt"])
    .index("by_channel_thread_turn", ["channelId", "threadId", "turnId"])
    .index("by_channel_thread_created", ["channelId", "threadId", "createdAt"]),
  authoringEvents: defineTable({
    turnId: v.id("authoringTurns"),
    createdAt: v.number(),
    kind: v.string(),
    state: v.string(),
    message: v.string(),
  }).index("by_turn_created", ["turnId", "createdAt"]),
  authoringToolActivities: defineTable({
    turnId: v.id("authoringTurns"),
    attempt: v.number(),
    sequence: v.number(),
    createdAt: v.number(),
    name: v.string(),
    status: v.string(),
    inputSummary: v.string(),
    outputSummary: v.string(),
    durationMs: v.number(),
  }).index("by_turn_attempt_sequence", ["turnId", "attempt", "sequence"]),
});
